#ifndef CONFIG_LOADER_H
#define CONFIG_LOADER_H

#include <stdio.h>

struct parcellation_t;  ///< forward declaration (defined in datasets/gifti.h)

/// @brief Structure to store all the configuration for the simulation
typedef struct simulation_configuration_t {

    // [general] information
    int neuron_type; // neuron type (LIF...) [opt]: LIF (1)
    size_t n_process; // number of CPU processes [opt]: 1
    int cuda; // simulation done in cuda [opt]: 0
    int multi_gpu; // [opt]: 0
    int learn; // 0: inference;  1: training [opt]: 0
    size_t batch_size; // batch size [opt]: 1
    size_t thrN; //  [opt]: 1
    int load_network; // 0: network file provided;  1: generate the network from file data;  2: do not generate the network [opt]: 0
    int load_dataset; // 0: dataset file provided;  1: generate the dataset from file data;  2: do not generate the dataset  [opt]: 0
    size_t n_neurons; // total neurons (for topology generation) [opt]: 0
    size_t n_neurons_medium; // medium-layer neurons in clustered topology [opt]: 0
    int x, y, z;

    // [simulation] data
    size_t time_steps; // time steps of the simulations
    size_t max_input_spikes; // maximum number of spikes in a input spike train // TODO: check wether necessary [opt]: = time_steps

    // [dataset] data
    char *dataset; // path to the file that contains the dataset
    char *labels; // path to the file that contains the labels of the dataset [opt]: depends on labels_provided
    int labels_provided; // wether dataset includes labels or not [opt]: No (0)
    size_t n_samples; // number of samples in the training set
    
    size_t n_classes; // number of classes in the dataset [opt]: 0
    size_t input_size; // number of features per each sample

    int shuffle_samples; // whether samples should be shuffled or not [opt]: No (0)
    size_t epochs; // number of epochs to simulate [opt]: 1

    // [output] data
    int store_generated_spikes, store_n_spikes, store_execution_times, store_network;
    char *generated_spikes_file; // file path to store the spike generated
    char *n_spikes_per_neuron_file; // file path to store the number of spikes generated by each sample
    char *execution_times_file; // file path to store the execution times
    char *store_network_file; // file path to store the final network
    FILE *f_gs, *f_ns, *f_et, *f_sn;

    // [network] section
    char *network_file; // file path to load the network from 
    char *network_neurons_file; // file path to load network neurons from 
    char *network_synapses_file; // file path to load network synapses from

    // * conectar clusters info
    char *network_neuron_cluster_file; // file path to load clusters info from

    // [parcellation] section – GIFTI-based parcel topology
    int enable_parcellation;
    int parcel_topology;            // flag: use parcel-based cluster distribution
    char *parcellation_file;        // path to .parc binary
    char *parcel_bold_file;         // path to .bold binary
    struct parcellation_t *parcellation; // loaded parcellation data (not owned by config)

} simulation_configuration_t;


/// @brief Read configuration parameters from configuration TOML file
/// @param file_name Name of the file to load configuration information from
/// @return Struct containing all the configuration data
simulation_configuration_t* load_configuration_params_from_toml(const char *file_name);



#endif